name: Test Application in Docker

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["build-and-push"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull latest Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/phenix-tracker:latest

      - name: Run Docker container
        run: |
          docker run -d --name phenix-tracker-test -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/phenix-tracker:latest
          sleep 5

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Run tests with Bruno
        run: |
          cd bruno
          bru run

      - name: Stop and remove container
        run: docker stop phenix-tracker-test && docker rm phenix-tracker-test
